config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :projects

  root 'application#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
  	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def welcome

	end

  	def after_sign_in_path_for(resource)
		projects_path
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :image, :budget)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/welcome.html.erb
<div class="container">
  	<div class="jumbotron jumbotron-fluid">
        <h1>Catarsinho</h1>
        <p class="lead">Bem-vindo ao catarsinho onde você pode criar pequenos projetos de arrecadação.</p>
        <p class="lead">Venha criar o seu projeto também! <%= link_to "Entrar", new_user_session_path, class: "btn btn-link" %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catarsinho</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <%= image_tag("logo_big.png", :alt => "rss feed", :class => "d-inline-block align-top") %>
      </a>

      <% if user_signed_in? %>
        
        <span class="nav-item">
          <%= link_to '+ Novo Projeto', new_project_path, class: "btn btn-info" %>
          <%= link_to "Meus Projetos", projects_path, class: "btn btn-info" %>
          <%= link_to "Sair", destroy_user_session_path, :method => :delete, class: "btn btn-dark" %>   
        </span>
      <% else %>
        <span class="nav-item">
          <%= link_to "Entrar", new_user_session_path, class: "btn btn-info" %>
        </span>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :project_image %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.text_field :budget, id: :project_budget %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= form_for @project, html: {multipart: true} do |f| %>
	
<div class="container">
  <div class="row">
  <h4>Editar Projeto</h4>
 <div class="col col-md-2"></div>
    <div class="col col-md-8">
  <form>
  <div class="form-group required">
    <label for="exampleInputEmail1" class='control-label'>Título do Projeto</label>
    <%= f.text_field :title, autocomplete: "off", class: "form-control", 'aria-describedby': "emailHelp", placeholder: "Ex: Fast Burguer Maker" %>
    <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
  </div>
  <div class="form-group required">
    <label for="exampleTextarea" class='control-label'>Descrição</label>
    <%= f.text_area :description, autocomplete: "off", placeholder: "Uma breve descrição do projeto", rows: 7, class: "form-control" %>
  </div>
  	<br>
  		<%= f.label "Image do projeto:" %> <br>

  		<% if @project.image? %>
  			<%= image_tag(@project.image, :alt => "rss feed", :class => "pull-left img-responsive thumb margin10 img-thumbnail") %>
  		<% end %>
		<%= f.file_field :image %>
	<br>
	<br>
	<%= f.label "Arrecadação de R$ 0,00", :id => "budget_label_id" %>
	<br>
	<%= f.range_field :budget, :in => 0..500, :step => '1', :id => "budget_id", :value => 0 %>
	<script type="text/javascript">
		(function() {
			var showElem = document.getElementById("budget_label_id");
			var elem = document.getElementById("budget_id");
			elem.addEventListener('change', function() {
				showElem.innerText = "Arrecadação de R$ " + elem.value + ",00";
				console.log(elem.value)
			});
		})();
	</script>
	<br>
	<br>
	<%= f.submit "Atualizar", class: "btn btn-primary btn-md" %> 
	<%= link_to 'Voltar para os meus projetos', projects_path, class: "btn btn-link" %>
	<br>
</div>


<% end %>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projetos</h1>

  <% @projects.each do |project| %>

    <div class="card mb-3" style="width: 18rem;">
      <%= image_tag(project.image, :class => "card-img-top") %>
      <div class="card-body">
        <h5 class="card-title"><%= project.title %></h5>
        <p class="card-text"><%= project.description %></p>
        <%= link_to 'Visualizar', project, class: "btn btn-primary" %>
        <%= link_to 'Editar', edit_project_path(project), class: "btn btn-primary" %>
      </div>
    </div>
    <hr>



  <% end %>
</div>

app/views/projects/new.html.erb
<%= form_for @project, html: {multipart: true} do |f| %>
	
<div class="container">
  <div class="row">
  <h4>Novo Projeto</h4>
 <div class="col col-md-2"></div>
    <div class="col col-md-8">
  <form>
  <div class="form-group required">
    <label for="exampleInputEmail1" class='control-label'>Título do Projeto</label>
    <%= f.text_field :title, autocomplete: "off", class: "form-control", 'aria-describedby': "emailHelp", placeholder: "Ex: Fast Burguer Maker" %>
    <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
  </div>
  <div class="form-group required">
    <label for="exampleTextarea" class='control-label'>Descrição</label>
    <%= f.text_area :description, autocomplete: "off", placeholder: "Uma breve descrição do projeto", rows: 7, class: "form-control" %>
  </div>
  	<br>
  		<%= f.label "Image do projeto:" %> <br>
		<%= f.file_field :image %>
	<br>
	<br>
	<%= f.label "Arrecadação de R$ 0,00", :id => "budget_label_id" %>
	<br>
	<%= f.range_field :budget, :in => 0..500, :step => '1', :id => "budget_id", :value => 0 %>
	<script type="text/javascript">
		(function() {
			var showElem = document.getElementById("budget_label_id");
			var elem = document.getElementById("budget_id");
			elem.addEventListener('change', function() {
				showElem.innerText = "Arrecadação de R$ " + elem.value + ",00";
				console.log(elem.value)
			});
		})();
	</script>
	<br>
	<br>
	<%= f.submit "Criar", class: "btn btn-primary btn-md" %> 
	<%= link_to 'Voltar para os meus projetos', projects_path, class: "btn btn-link" %>
	<br>
</div>


<% end %>

app/views/projects/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @project.title %></h1>
  <%= image_tag(@project.image) %>
  <p class="lead">
  	<%= @project.description %>
  </p>
  <p>Arrecadação R$ <%= @project.budget %>,00 </p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Editar', edit_project_path(@project), class: "btn btn-link" %> |
	<%= link_to 'Voltar', projects_path, class: "btn btn-link" %>
  </p>
</div>